# Basic config
baseURL = "/"
theme = "hugo-trainsh"
copyright = "Grrru (CC BY 4.0)"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
publishDir = "docs"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[markup]
[markup.highlight]
lineNos = false
lineNumbersInTable = false
noClasses = true
style = "catppuccin-frappe"

[languages]
[languages.en]
title = "Grrru Blog"
languageName = "English"
LanguageCode = "en-US"
contentDir = "content"
weight = 1
[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1
[[languages.en.menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[languages.kr]
title = "Grrru Blog"
languageName = "한국어"
LanguageCode = "ko-KR"
contentDir = "content.kr"
weight = 2
[[languages.kr.menu.main]]
name = "Home"
url = "/"
weight = 1
[[languages.kr.menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[params]
description = "Blog Demo"
favicon = "images/favicon.svg"
dateFormat = "2006-01-02"
mainSections = ["blog"]

[params.home]
[params.home.recent]
limit = 5

[params.social]
github = "https://github.com/grrru"
linkedin = "https://www.linkedin.com/in/grrru/"
email = "gruns0989@naver.com"

[params.author]
name = "grrru"
email = "gruns0989@naver.com"
